# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libghidra/analysis.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'libghidra/analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18libghidra/analysis.proto\x12\tlibghidra\"\x95\x01\n\x11\x41nalysisJobRecord\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x17\n\x0fstarted_unix_ms\x18\x04 \x01(\x03\x12\x15\n\rended_unix_ms\x18\x05 \x01(\x03\x12\x12\n\nelapsed_ms\x18\x06 \x01(\x04\x12\x0f\n\x07message\x18\x07 \x01(\t\"$\n\x14StartAnalysisRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\"B\n\x15StartAnalysisResponse\x12)\n\x03job\x18\x01 \x01(\x0b\x32\x1c.libghidra.AnalysisJobRecord\"\x19\n\x17ListAnalysisJobsRequest\"F\n\x18ListAnalysisJobsResponse\x12*\n\x04jobs\x18\x01 \x03(\x0b\x32\x1c.libghidra.AnalysisJobRecord\"\'\n\x15\x43\x61ncelAnalysisRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\"+\n\x16\x43\x61ncelAnalysisResponse\x12\x11\n\tcancelled\x18\x01 \x01(\x08\x32\x99\x02\n\x0f\x41nalysisService\x12R\n\rStartAnalysis\x12\x1f.libghidra.StartAnalysisRequest\x1a .libghidra.StartAnalysisResponse\x12[\n\x10ListAnalysisJobs\x12\".libghidra.ListAnalysisJobsRequest\x1a#.libghidra.ListAnalysisJobsResponse\x12U\n\x0e\x43\x61ncelAnalysis\x12 .libghidra.CancelAnalysisRequest\x1a!.libghidra.CancelAnalysisResponseB\x1c\n\tlibghidraB\rAnalysisProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libghidra.analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlibghidraB\rAnalysisProtoP\001'
  _globals['_ANALYSISJOBRECORD']._serialized_start=40
  _globals['_ANALYSISJOBRECORD']._serialized_end=189
  _globals['_STARTANALYSISREQUEST']._serialized_start=191
  _globals['_STARTANALYSISREQUEST']._serialized_end=227
  _globals['_STARTANALYSISRESPONSE']._serialized_start=229
  _globals['_STARTANALYSISRESPONSE']._serialized_end=295
  _globals['_LISTANALYSISJOBSREQUEST']._serialized_start=297
  _globals['_LISTANALYSISJOBSREQUEST']._serialized_end=322
  _globals['_LISTANALYSISJOBSRESPONSE']._serialized_start=324
  _globals['_LISTANALYSISJOBSRESPONSE']._serialized_end=394
  _globals['_CANCELANALYSISREQUEST']._serialized_start=396
  _globals['_CANCELANALYSISREQUEST']._serialized_end=435
  _globals['_CANCELANALYSISRESPONSE']._serialized_start=437
  _globals['_CANCELANALYSISRESPONSE']._serialized_end=480
  _globals['_ANALYSISSERVICE']._serialized_start=483
  _globals['_ANALYSISSERVICE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
