# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libghidra/common.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'libghidra/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16libghidra/common.proto\x12\tlibghidra\"<\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"+\n\nPagination\x12\r\n\x05limit\x18\x01 \x01(\r\x12\x0e\n\x06offset\x18\x02 \x01(\r\"*\n\x0c\x41\x64\x64ressRange\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04*\x82\x01\n\x0eShutdownPolicy\x12\x1f\n\x1bSHUTDOWN_POLICY_UNSPECIFIED\x10\x00\x12\x18\n\x14SHUTDOWN_POLICY_SAVE\x10\x01\x12\x1b\n\x17SHUTDOWN_POLICY_DISCARD\x10\x02\x12\x18\n\x14SHUTDOWN_POLICY_NONE\x10\x03\x42\x1a\n\tlibghidraB\x0b\x43ommonProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libghidra.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlibghidraB\013CommonProtoP\001'
  _globals['_SHUTDOWNPOLICY']._serialized_start=189
  _globals['_SHUTDOWNPOLICY']._serialized_end=319
  _globals['_ERRORDETAIL']._serialized_start=37
  _globals['_ERRORDETAIL']._serialized_end=97
  _globals['_PAGINATION']._serialized_start=99
  _globals['_PAGINATION']._serialized_end=142
  _globals['_ADDRESSRANGE']._serialized_start=144
  _globals['_ADDRESSRANGE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
