# Copyright (c) 2024-2026 Elias Bachaalany
# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Known Ghidra language and compiler IDs embedded with libghidra."""

from __future__ import annotations

# Generated from Ghidra processor *.ldefs files by cpp/embed_specs.py.
LANGUAGE_COMPILERS: dict[str, tuple[str, ...]] = {
    '6502:LE:16:default': ('default',),
    '65C02:LE:16:default': ('default',),
    '68000:BE:32:Coldfire': ('default', 'register',),
    '68000:BE:32:MC68020': ('default',),
    '68000:BE:32:MC68030': ('default',),
    '68000:BE:32:default': ('default',),
    '6805:BE:16:default': ('default',),
    '6809:BE:16:default': ('default',),
    '80251:BE:24:default': ('default',),
    '80390:BE:24:default': ('default',),
    '8048:LE:16:default': ('default',),
    '8051:BE:16:default': ('Archimedes', 'default',),
    '8051:BE:24:mx51': ('default',),
    '8085:LE:16:default': ('default',),
    'AARCH64:BE:32:ilp32': ('default', 'golang',),
    'AARCH64:BE:64:v8A': ('default', 'golang',),
    'AARCH64:LE:32:ilp32': ('default', 'golang',),
    'AARCH64:LE:64:AppleSilicon': ('default', 'golang', 'swift',),
    'AARCH64:LE:64:v8A': ('default', 'golang', 'swift', 'windows',),
    'ARM:BE:32:Cortex': ('apcs', 'default',),
    'ARM:BE:32:v4': ('apcs', 'default',),
    'ARM:BE:32:v4t': ('apcs', 'default',),
    'ARM:BE:32:v5': ('apcs', 'default',),
    'ARM:BE:32:v5t': ('apcs', 'default',),
    'ARM:BE:32:v6': ('apcs', 'default',),
    'ARM:BE:32:v7': ('apcs', 'default',),
    'ARM:BE:32:v8': ('apcs', 'default',),
    'ARM:BE:32:v8-m': ('apcs', 'default',),
    'ARM:BE:32:v8T': ('apcs', 'default',),
    'ARM:LE:32:Cortex': ('apcs', 'default',),
    'ARM:LE:32:v4': ('apcs', 'default',),
    'ARM:LE:32:v4t': ('apcs', 'default',),
    'ARM:LE:32:v5': ('apcs', 'default',),
    'ARM:LE:32:v5t': ('apcs', 'default',),
    'ARM:LE:32:v6': ('apcs', 'default',),
    'ARM:LE:32:v7': ('apcs', 'default', 'windows',),
    'ARM:LE:32:v8': ('apcs', 'default', 'windows',),
    'ARM:LE:32:v8-m': ('apcs', 'default',),
    'ARM:LE:32:v8T': ('apcs', 'default', 'windows',),
    'ARM:LEBE:32:v7LEInstruction': ('apcs', 'default', 'windows',),
    'ARM:LEBE:32:v8LEInstruction': ('apcs', 'default', 'windows',),
    'BPF:LE:32:default': ('default',),
    'CP1600:BE:16:default': ('default',),
    'CR16C:LE:16:default': ('default',),
    'DATA:BE:64:default': ('pointer16', 'pointer32', 'pointer64',),
    'DATA:LE:64:default': ('pointer16', 'pointer32', 'pointer64',),
    'Dalvik:LE:32:DEX_Android10': ('default',),
    'Dalvik:LE:32:DEX_Android11': ('default',),
    'Dalvik:LE:32:DEX_Android12': ('default',),
    'Dalvik:LE:32:DEX_Android13': ('default',),
    'Dalvik:LE:32:DEX_Base': ('default',),
    'Dalvik:LE:32:DEX_KitKat': ('default',),
    'Dalvik:LE:32:DEX_Lollipop': ('default',),
    'Dalvik:LE:32:DEX_Nougat': ('default',),
    'Dalvik:LE:32:DEX_Oreo': ('default',),
    'Dalvik:LE:32:DEX_Pie': ('default',),
    'Dalvik:LE:32:Marshmallow': ('default',),
    'Dalvik:LE:32:ODEX_KitKat': ('default',),
    'Dalvik:LE:32:default': ('default',),
    'H6309:BE:16:default': ('default',),
    'HC-12:BE:16:default': ('default',),
    'HC05:BE:16:M68HC05TB': ('default',),
    'HC05:BE:16:default': ('default',),
    'HC08:BE:16:MC68HC908QY4': ('default',),
    'HC08:BE:16:default': ('default',),
    'HCS-12:BE:24:default': ('default',),
    'HCS-12X:BE:24:default': ('default',),
    'HCS08:BE:16:MC9S08GB60': ('default',),
    'HCS08:BE:16:default': ('default',),
    'HCS12:BE:24:default': ('default',),
    'JVM:BE:32:default': ('default',),
    'Loongarch:LE:32:ilp32d': ('default',),
    'Loongarch:LE:32:ilp32f': ('default',),
    'Loongarch:LE:64:lp64d': ('default',),
    'Loongarch:LE:64:lp64f': ('default',),
    'M16C/60:LE:16:default': ('default',),
    'M16C/80:LE:16:default': ('default',),
    'M8C:BE:16:default': ('default',),
    'MCS96:LE:16:default': ('default',),
    'MIPS:BE:32:R6': ('default',),
    'MIPS:BE:32:default': ('default', 'eabi', 'windows',),
    'MIPS:BE:32:micro': ('default',),
    'MIPS:BE:64:64-32R6addr': ('default', 'n32', 'o32', 'o64',),
    'MIPS:BE:64:64-32addr': ('default', 'n32', 'o32', 'o64',),
    'MIPS:BE:64:R6': ('default',),
    'MIPS:BE:64:default': ('default',),
    'MIPS:BE:64:micro': ('default',),
    'MIPS:BE:64:micro64-32addr': ('default', 'n32', 'o32', 'o64',),
    'MIPS:LE:32:R6': ('default',),
    'MIPS:LE:32:default': ('default', 'eabi', 'windows',),
    'MIPS:LE:32:micro': ('default', 'windows',),
    'MIPS:LE:64:64-32R6addr': ('default', 'n32', 'o32', 'o64', 'windows',),
    'MIPS:LE:64:64-32addr': ('default', 'n32', 'o32', 'o64', 'windows',),
    'MIPS:LE:64:R6': ('default', 'windows',),
    'MIPS:LE:64:default': ('default', 'windows',),
    'MIPS:LE:64:micro': ('default', 'windows',),
    'MIPS:LE:64:micro64-32addr': ('default', 'n32', 'o32', 'o64', 'windows',),
    'NDS32:BE:32:default': ('default',),
    'NDS32:LE:32:default': ('default',),
    'PIC-12:LE:16:PIC-12C5xx': ('default',),
    'PIC-16:LE:16:PIC-16': ('default',),
    'PIC-16:LE:16:PIC-16C5x': ('default',),
    'PIC-16:LE:16:PIC-16F': ('default',),
    'PIC-17:LE:16:PIC-17C7xx': ('default',),
    'PIC-18:LE:24:PIC-18': ('default',),
    'PIC-24E:LE:24:default': ('default',),
    'PIC-24F:LE:24:default': ('default',),
    'PIC-24H:LE:24:default': ('default',),
    'PowerPC:BE:32:4xx': ('default',),
    'PowerPC:BE:32:MPC8270': ('default',),
    'PowerPC:BE:32:QUICC': ('default',),
    'PowerPC:BE:32:default': ('default', 'macosx',),
    'PowerPC:BE:32:e500': ('default',),
    'PowerPC:BE:32:e500mc': ('default',),
    'PowerPC:BE:64:64-32addr': ('default',),
    'PowerPC:BE:64:A2-32addr': ('default',),
    'PowerPC:BE:64:A2ALT': ('default',),
    'PowerPC:BE:64:A2ALT-32addr': ('default',),
    'PowerPC:BE:64:VLE-32addr': ('default',),
    'PowerPC:BE:64:VLEALT-32addr': ('default',),
    'PowerPC:BE:64:default': ('default', 'macosx',),
    'PowerPC:LE:32:4xx': ('default', 'windows',),
    'PowerPC:LE:32:QUICC': ('default', 'windows',),
    'PowerPC:LE:32:default': ('default', 'windows',),
    'PowerPC:LE:32:e500': ('default',),
    'PowerPC:LE:32:e500mc': ('default',),
    'PowerPC:LE:64:64-32addr': ('default', 'windows',),
    'PowerPC:LE:64:A2-32addr': ('default', 'windows',),
    'PowerPC:LE:64:A2ALT': ('default',),
    'PowerPC:LE:64:A2ALT-32addr': ('default', 'windows',),
    'PowerPC:LE:64:default': ('default',),
    'RISCV:LE:32:AndeStar_v5': ('gcc',),
    'RISCV:LE:32:default': ('gcc',),
    'RISCV:LE:64:default': ('gcc',),
    'SuperH4:BE:32:default': ('default',),
    'SuperH4:LE:32:default': ('default', 'windows',),
    'SuperH:BE:32:SH-1': ('default',),
    'SuperH:BE:32:SH-2': ('default',),
    'SuperH:BE:32:SH-2A': ('default',),
    'TI_MSP430:LE:16:default': ('default',),
    'TI_MSP430X:LE:32:default': ('default',),
    'Toy:BE:32:builder': ('default',),
    'Toy:BE:32:builder.align2': ('default',),
    'Toy:BE:32:default': ('default',),
    'Toy:BE:32:posStack': ('posStack',),
    'Toy:BE:32:wordSize2': ('default',),
    'Toy:BE:64:default': ('default', 'long8',),
    'Toy:BE:64:harvard': ('default',),
    'Toy:BE:64:harvard_rev': ('default',),
    'Toy:LE:32:builder': ('default',),
    'Toy:LE:32:builder.align2': ('default',),
    'Toy:LE:32:default': ('default',),
    'Toy:LE:32:wordSize2': ('default',),
    'Toy:LE:64:default': ('default',),
    'V850:LE:32:default': ('default',),
    'Xtensa:BE:32:default': ('default',),
    'Xtensa:LE:32:default': ('default',),
    'avr32:BE:32:default': ('default',),
    'avr8:LE:16:atmega256': ('gcc',),
    'avr8:LE:16:default': ('gcc', 'iarV1', 'imgCraftV8',),
    'avr8:LE:16:extended': ('gcc',),
    'avr8:LE:24:xmega': ('gcc',),
    'dsPIC30F:LE:24:default': ('default',),
    'dsPIC33C:LE:24:default': ('default',),
    'dsPIC33E:LE:24:default': ('default',),
    'dsPIC33F:LE:24:default': ('default',),
    'eBPF:BE:64:default': ('default',),
    'eBPF:LE:64:default': ('default',),
    'pa-risc:BE:32:default': ('default',),
    'sparc:BE:32:default': ('default',),
    'sparc:BE:64:default': ('default',),
    'tricore:LE:32:default': ('default',),
    'tricore:LE:32:tc172x': ('default',),
    'tricore:LE:32:tc176x': ('default',),
    'tricore:LE:32:tc29x': ('default',),
    'x86:LE:16:Protected Mode': ('default',),
    'x86:LE:16:Real Mode': ('default',),
    'x86:LE:32:System Management Mode': ('default',),
    'x86:LE:32:default': ('borlandcpp', 'borlanddelphi', 'clangwindows', 'gcc', 'golang', 'windows',),
    'x86:LE:64:compat32': ('gcc', 'windows',),
    'x86:LE:64:default': ('clangwindows', 'gcc', 'golang', 'swift', 'windows',),
    'z180:LE:16:default': ('default',),
    'z182:LE:16:default': ('default',),
    'z80:LE:16:default': ('default',),
    'z8401x:LE:16:default': ('default',),
}

LANGUAGE_IDS: frozenset[str] = frozenset(LANGUAGE_COMPILERS)
