# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libghidra/memory.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'libghidra/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from libghidra import common_pb2 as libghidra_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16libghidra/memory.proto\x12\tlibghidra\x1a\x16libghidra/common.proto\"3\n\x10ReadBytesRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\r\"!\n\x11ReadBytesResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"2\n\x11WriteBytesRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"+\n\x12WriteBytesResponse\x12\x15\n\rbytes_written\x18\x01 \x01(\r\"*\n\tBytePatch\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"?\n\x16PatchBytesBatchRequest\x12%\n\x07patches\x18\x02 \x03(\x0b\x32\x14.libghidra.BytePatch\"E\n\x17PatchBytesBatchResponse\x12\x13\n\x0bpatch_count\x18\x01 \x01(\r\x12\x15\n\rbytes_written\x18\x02 \x01(\r\"\xe5\x01\n\x11MemoryBlockRecord\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rstart_address\x18\x02 \x01(\x04\x12\x13\n\x0b\x65nd_address\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x01(\x04\x12\x0f\n\x07is_read\x18\x05 \x01(\x08\x12\x10\n\x08is_write\x18\x06 \x01(\x08\x12\x12\n\nis_execute\x18\x07 \x01(\x08\x12\x13\n\x0bis_volatile\x18\x08 \x01(\x08\x12\x16\n\x0eis_initialized\x18\t \x01(\x08\x12\x13\n\x0bsource_name\x18\n \x01(\t\x12\x0f\n\x07\x63omment\x18\x0b \x01(\t\">\n\x17ListMemoryBlocksRequest\x12#\n\x04page\x18\x02 \x01(\x0b\x32\x15.libghidra.Pagination\"H\n\x18ListMemoryBlocksResponse\x12,\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x1c.libghidra.MemoryBlockRecord2\xd9\x02\n\rMemoryService\x12\x46\n\tReadBytes\x12\x1b.libghidra.ReadBytesRequest\x1a\x1c.libghidra.ReadBytesResponse\x12I\n\nWriteBytes\x12\x1c.libghidra.WriteBytesRequest\x1a\x1d.libghidra.WriteBytesResponse\x12X\n\x0fPatchBytesBatch\x12!.libghidra.PatchBytesBatchRequest\x1a\".libghidra.PatchBytesBatchResponse\x12[\n\x10ListMemoryBlocks\x12\".libghidra.ListMemoryBlocksRequest\x1a#.libghidra.ListMemoryBlocksResponseB\x1a\n\tlibghidraB\x0bMemoryProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libghidra.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlibghidraB\013MemoryProtoP\001'
  _globals['_READBYTESREQUEST']._serialized_start=61
  _globals['_READBYTESREQUEST']._serialized_end=112
  _globals['_READBYTESRESPONSE']._serialized_start=114
  _globals['_READBYTESRESPONSE']._serialized_end=147
  _globals['_WRITEBYTESREQUEST']._serialized_start=149
  _globals['_WRITEBYTESREQUEST']._serialized_end=199
  _globals['_WRITEBYTESRESPONSE']._serialized_start=201
  _globals['_WRITEBYTESRESPONSE']._serialized_end=244
  _globals['_BYTEPATCH']._serialized_start=246
  _globals['_BYTEPATCH']._serialized_end=288
  _globals['_PATCHBYTESBATCHREQUEST']._serialized_start=290
  _globals['_PATCHBYTESBATCHREQUEST']._serialized_end=353
  _globals['_PATCHBYTESBATCHRESPONSE']._serialized_start=355
  _globals['_PATCHBYTESBATCHRESPONSE']._serialized_end=424
  _globals['_MEMORYBLOCKRECORD']._serialized_start=427
  _globals['_MEMORYBLOCKRECORD']._serialized_end=656
  _globals['_LISTMEMORYBLOCKSREQUEST']._serialized_start=658
  _globals['_LISTMEMORYBLOCKSREQUEST']._serialized_end=720
  _globals['_LISTMEMORYBLOCKSRESPONSE']._serialized_start=722
  _globals['_LISTMEMORYBLOCKSRESPONSE']._serialized_end=794
  _globals['_MEMORYSERVICE']._serialized_start=797
  _globals['_MEMORYSERVICE']._serialized_end=1142
# @@protoc_insertion_point(module_scope)
