# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libghidra/rpc.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'libghidra/rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13libghidra/rpc.proto\x12\tlibghidra\x1a\x19google/protobuf/any.proto\"C\n\nRpcRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\x82\x01\n\x0bRpcResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12%\n\x07payload\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08revision\x18\x05 \x01(\x04\x32\x43\n\nRpcService\x12\x35\n\x04\x43\x61ll\x12\x15.libghidra.RpcRequest\x1a\x16.libghidra.RpcResponseB\x17\n\tlibghidraB\x08RpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libghidra.rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlibghidraB\010RpcProtoP\001'
  _globals['_RPCREQUEST']._serialized_start=61
  _globals['_RPCREQUEST']._serialized_end=128
  _globals['_RPCRESPONSE']._serialized_start=131
  _globals['_RPCRESPONSE']._serialized_end=261
  _globals['_RPCSERVICE']._serialized_start=263
  _globals['_RPCSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
