# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libghidra/xrefs.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'libghidra/xrefs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from libghidra import common_pb2 as libghidra_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15libghidra/xrefs.proto\x12\tlibghidra\x1a\x16libghidra/common.proto\"\xcf\x01\n\nXrefRecord\x12\x14\n\x0c\x66rom_address\x18\x01 \x01(\x04\x12\x12\n\nto_address\x18\x02 \x01(\x04\x12\x15\n\roperand_index\x18\x03 \x01(\x05\x12\x10\n\x08ref_type\x18\x04 \x01(\t\x12\x12\n\nis_primary\x18\x05 \x01(\x08\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x11\n\tsymbol_id\x18\x07 \x01(\x03\x12\x13\n\x0bis_external\x18\x08 \x01(\x08\x12\x11\n\tis_memory\x18\t \x01(\x08\x12\x0f\n\x07is_flow\x18\n \x01(\x08\"_\n\x10ListXrefsRequest\x12&\n\x05range\x18\x02 \x01(\x0b\x32\x17.libghidra.AddressRange\x12#\n\x04page\x18\x03 \x01(\x0b\x32\x15.libghidra.Pagination\"9\n\x11ListXrefsResponse\x12$\n\x05xrefs\x18\x01 \x03(\x0b\x32\x15.libghidra.XrefRecord2V\n\x0cXrefsService\x12\x46\n\tListXrefs\x12\x1b.libghidra.ListXrefsRequest\x1a\x1c.libghidra.ListXrefsResponseB\x19\n\tlibghidraB\nXrefsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libghidra.xrefs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tlibghidraB\nXrefsProtoP\001'
  _globals['_XREFRECORD']._serialized_start=61
  _globals['_XREFRECORD']._serialized_end=268
  _globals['_LISTXREFSREQUEST']._serialized_start=270
  _globals['_LISTXREFSREQUEST']._serialized_end=365
  _globals['_LISTXREFSRESPONSE']._serialized_start=367
  _globals['_LISTXREFSRESPONSE']._serialized_end=424
  _globals['_XREFSSERVICE']._serialized_start=426
  _globals['_XREFSSERVICE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
